
[dependencies]
pandas = ">=2.3.3,<3"
pandas-stubs = ">=2.3.3.251201,<3"
python = ">=3.13.9,<3.14"
selenium = ">=4.38.0,<5"

[tasks]
updt = "pixi update && pixi ls -x"
upgd = "pixi upgrade --exclude python && pixi run updt"

[workspace]
channels = ["conda-forge"]
name = "Selenium"
platforms = ["linux-64", "win-64", "osx-arm64"]
